##
# Example Ansible playbook that uses the PostgreSQL module.
#
# This installs PostgreSQL on an Ubuntu system, creates a database called
# "myapp" and a user called "django" with password "mysupersecretpassword"
# with access to the "myapp" database.
#
---

- name: ensure packages are installed
  apt:  pkg={{item}} state=latest
  with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2
      - php5-pgsql

- name: ensure database is created
  sudo_user: postgres
  postgresql_db: name={{database_name}}

- name: ensure user has access to database
  sudo_user: postgres
  postgresql_user: db={{database_name}} name={{database_user}} password={{database_password}} priv=ALL

- name: ensure user does not have unnecessary privilege
  sudo_user: postgres
  postgresql_user: name={{database_user}} role_attr_flags=NOSUPERUSER,NOCREATEDB